### PR TITLE
fix geopandas

### PR DESCRIPTION
**Pull request by pat-schmitt**
First attempt to fix for new geopandas version

### CODE REVIEW

**Comment by TimoRoth** [comment]
I don't think this was the right target repository?

**Comment by pat-schmitt** [comment]
Ok, I thought I add it to you PR when I merge here. Where should I add the change than?

**Comment by TimoRoth** [comment]
Ideally just to the main repository.
It should pass tests with the old version as well after all, and the non-pinned images already have the new geopandas version, so both will be tested.

**Comment by pat-schmitt** [comment]
Ok, so I will open a new PR. Thanks

**Pull request closed without merging**
